### ISSUE TITLE
Having trouble mounting SD card

### ISSUE THREAD

**Issue by tthayer** [ExXeptional/micropython#16]
I have the SD card wired up and the launchpad no longer throws an error about being unable to mount the SD card but I can't seem to figure out how to mount the filesystem or do anything with it. Do you have any tips for getting it working? I have a few of these boards so I really appreciate the work you put in to porting MicroPython over!

**Comment by rk-exxec** [comment]
Hey! 
I guess you are using the provided binary file?
It's pretty old and I am currently working on a new release with new features and bugfixes (eg error if no SD card is connected).

That said, if there are a boot.py and a main.py on the sd card they should be run when the board boots up. That's all that it currently supports.

You can for example define custom classes in main and then they would be available on the command line.

You can use the tool mpfshell where you can also access the filesystem directly.

I hope that helped a bit. If not, please tell me. It helps me improve this port.

**Comment by tthayer** [comment]
I compiled it fresh from the branch (which was a fun one to figure out on OSX) but didn't realize I had to put files on the card! I'm new to micropython in general so please forgive my ignorance here.
mpfshell throws an error about not being able to import 'sys' so I'm guessing this is part of my problem.

**Comment by tthayer** [comment]
It looks like the code to autogenerate a boot.py is commented out. Is there a recommended boot.py config?

**Comment by rk-exxec** [comment]
> I compiled it fresh from the branch

Which branch did you use?

> mpfshell throws an error

could you show me the commands you're using and the error?

> Is there a recommended boot.py config?

from what I understood, it totally depends on your use case. I would think one does initial setup there. But it is not required. You can just leave it blank if you want.

As simple example you could put this in the main.py:
```python
from umachine import Pin

p_led = Pin('PF2', Pin.OUT)
p_led.on()
```
this should turn on one of the onboard LEDs (i don't exactly remember the correct Pin but you can change it)
and then switch to the command prompt

then you can at least check if the files are read correctly.

**Comment by tthayer** [comment]
1. I used the `tiva_from_stable` branch
2. mpfshell output: `('exception', b'', b'Traceback (most recent call last):\r\n  File "<stdin>", in <module>\r\nImportError: no module named \'sys\'\r\n')`

Running your example code from the REPL does work but the same code in the boot.py doesn't have any effect. I see this when I check the card status:
```
>>> import umachine as machine
>>> sd = machine.SD()
>>> sd.present()
False
```

**Comment by rk-exxec** [comment]
I see, did you test with the pre built binary file under releases? If not please try that. 
The branch was recently updated to the new micropython version and I haven't tested it yet.

**Comment by tthayer** [comment]
I tried the pre-built binary yesterday and wasn't able to get any response from the board either from boot.py or from the REPL. I have another board I'll try it on too today.

**Comment by rk-exxec** [comment]
I will test it soon myself. Have to re-setup my toolchain bc new PC.

**Comment by tthayer** [comment]
I tried to use the prebuilt binary and the board didn’t like it. I got no
response at the terminal.

**Comment by rk-exxec** [comment]
Hey, I think I fixed it. Sorry it took so long!

If there are still issues please let me know!

**Comment by rk-exxec** [comment]
Also, I changed the Pins for the SD Card, please check the Readme!

**Comment by tthayer** [comment]
Thanks for looking into this! I'm still having trouble and I think part of the trouble is that the SPI interface for SD cards doesn't seem to have a Card Detect pin as far as I can understand. Can you describe how you're attaching the SD reader?

**Comment by rk-exxec** [comment]
You have to connect the sd card exactly like this:
| Board Pin | SD-Pin (SPI / SDIO)    |
| --------: | :--------------------- |
|       PE4 | Card Detect (CD / DET) |
|       PA2 | Clock (SCK / CLK)      |
|       PA3 | Chip Select (CS / D3)  |
|       PA4 | Data Out (MISO / D0)   |
|       PA5 | Data In (MOSI / CMD)   |

Don't forget GND and 3V3. I am using a sparkfun or adafruit SD Breakout board for that.  
If that doesn't work either, could you send me a picture of your setup?

**Comment by tthayer** [comment]
ah I see. I am using a microSD-SD adapter with wires soldered to the adapter pins directly so I've been trying to use something like the diagram here to map board pins to SD pins: https://electronics.stackexchange.com/questions/278852/sd-card-detect-in-spi-mode
Though I also tried to just jumper the Card Detect pin to ground and that didn't work before either. I'll try it again.

**Comment by rk-exxec** [comment]
The CD pin was bugged before. The jumper should work now.
Just incase: Did you use the pinout from the micro SD? The normal SD pinout is slightly different 
https://www.matrixtsl.com/wiki/index.php?title=File:Sd-card-pinout.jpg

**Comment by tthayer** [comment]
That worked! Thanks for your work on this.

**Comment by rk-exxec** [comment]
Glad it works now. Please feel free to report any other issues you come across. It really helps me improve this port!
