### ISSUE TITLE
Build on Linux

### ISSUE THREAD

**Issue by mgaman** [ExXeptional/micropython#19]
I tried following the lines:
**git clone https://github.com/rk-exxec/micropython.git && git checkout tiva_from_stable
cd ./micropython**

but the 'git checkout' part failed as no repository was found
Redoing as:
**git clone https://github.com/rk-exxec/micropython.git
cd ./micropython
git checkout tiva_from_stable**
worked just fine

After flashing the image to the launchpad I got REPL working but no modules are present e.g. machine, os. What am I doing wrong?

**Comment by rk-exxec** [comment]
Hey, thanks for letting me know, will change that in the Readme

As for the modules...
did you try importing the modules first? (you also need to prepend a 'u', so umachine, uos etc)
` from umachine import Pin`  etc.

**Comment by mgaman** [comment]
thanks for the hint, umachine works fine

**Comment by mgaman** [comment]
According to the sources and the log from make, the module utime is included. However **import utime** says no such module

**Comment by rk-exxec** [comment]
Yes, its currently not functional. But we're working on it.
We need to implement the hardware timer first.

Did you have any special use case?

**Comment by mgaman** [comment]
Not really, I was mostly just curious. In my work I've used the launchpad for dozens of projects, always in C and using code composer + tivaware. I thought that using python would drag me into the 21st century
